let demoTransactions = [
  {id: 1,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyLandlord',
  scheduledDate:'',
  dueDate:'',
  amount: 4000},
  {id: 2,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyContractor',
  scheduledDate:'',
  dueDate:'',
  amount: 2000},
  {id: 3,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MySupplier',
  scheduledDate:'',
  dueDate:'',
  amount: 1000},
  {id: 4,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyElectricity',
  scheduledDate:'',
  dueDate:'',
  amount: 800},
  {id: 5,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyWater',
  scheduledDate:'',
  dueDate:'',
  amount: 100},
  {id: 6,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyCleaning',
  scheduledDate:'',
  dueDate:'',
  amount: 400},
  {id: 7,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyPayroll',
  scheduledDate:'',
  dueDate:'',
  amount: 7000},
  {id: 8,
  type: 'Income',
  accountName: 'CASH',
  payee: 'FirstData',
  scheduledDate:'',
  dueDate:'',
  amount: 2000},
  {id: 9,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'CompanyCar',
  scheduledDate:'',
  dueDate:'',
  amount: 575},
  {id: 10,
  type: 'Income',
  accountName: 'CASH',
  payee: 'CustomerRcvbl',
  scheduledDate:'',
  dueDate:'',
  amount: 975},
  {id: 11,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyLandlord',
  scheduledDate:'',
  dueDate:'',
  amount: 4000},
  {id: 12,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyElectricity',
  scheduledDate:'',
  dueDate:'',
  amount: 800},
  {id: 13,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'MyWater',
  scheduledDate:'',
  dueDate:'',
  amount: 100},
  {id: 14,
  type: 'Expense',
  accountName: 'CASH',
  payee: 'CompanyCar',
  scheduledDate:'',
  dueDate:'',
  amount: 575}
];

export {demoTransactions};
